version: "3.8"
name: "geoutil"

services:

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "$PWD/volume:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  dynamoadmin:
    build:
      context: ./dynamoadmin
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://localhost:4569

  valhalla:
    image: ghcr.io/gis-ops/docker-valhalla/valhalla:latest
    ports:
      - "8002:8002"
    volumes:
      - "$PWD/custom_files:/custom_files"