version: "3.8"
name: "geoutil"

services:

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  valhalla:
    container_name: "motor-valhalla"
    image: ghcr.io/gis-ops/docker-valhalla/valhalla:latest
    ports:
      - "8002:8002"
    volumes:
      - "$PWD/valhalla:/custom_files"

  vroom:
    container_name: "motor-vroom"
    image: vroomvrp/vroom-docker:v1.13.0
    ports:
      - "3000:3000"
    environment:
      - VROOM_ROUTER=valhalla
    volumes:
      - "$PWD/vroom/conf:/conf"

  osrm:
    container_name: "osrm"
    image: osrm/osrm-backend
    ports:
      - "5000:5000"
    command:
      - /bin/sh
      - -c
      - |
        osrm-extract -p /opt/car.lua /data/berlin-latest.osm.pbf
        osrm-partition /data/berlin-latest.osrm
        osrm-customize /data/berlin-latest.osrm
        osrm-routed --algorithm mld /data/berlin-latest.osrm
    volumes:
      - "$PWD/osrm:/data"



